### ISSUE TITLE
Some services failed to build

### ISSUE THREAD

**Issue by Gargi415** [willswire/balena-dashboards#14]
When I am trying to build and push code to raspberry I'am getting error:

[electron]  Successfully built 44984bc9ca2f
[Info]      Uploading images
[Success]   Successfully uploaded images
[Error]     Some services failed to build:
[Error]       Service: vnc
[Error]         Error: manifest for balenalib/raspberrypi4-64-alpine-python:latest not found
[Info]      Built on arm01
[Error]     Not deploying release.
Remote build failed

How can I fix it?

**Comment by willswire** [comment]
Looks like you were trying to build on a raspberry pi v4. I haven’t tested this project on that hardware yet. You can start by forking this repository, and modifying the base image for the VMC container. You’re getting the error because it is unable to find an alpine image with python installed for the 64-bit architecture of the raspberry pi 4.
